### ISSUE TITLE
compilation issues

### ISSUE THREAD

**Issue by cocoabox** [sdancer75/DOS-GUI-Norton-Style#1]
Hi! Very nice work! This is what I've been looking for.
For the QSORT app, 
- can you please provide the source code, 
- is there an English version available?
- can I use other fonts for this app?

Or, if you could provide a simple Hello wrold App in TP that'd be really nice

Many thanks!

**Comment by sdancer75** [comment]
Hi, there, 

The DOS-GUI-Norton-Style is a library. The QSort application is just an app that uses that library and is not a prerequisite to use it. I believe there is some test files you can begin work with this.

Unfortunately, I lost the source code of the qsort app. Maybe it is somewhere inside my hundreds of backup CDs but I haven't restored it yet (some of them are not readable anymore). This code is pretty old and I hardly remember anything of this, but yes, you can use other languages when you build a new code from the sources since it uses standard ASCII code. 

The Greek letters (and any other language you desire) are positioned from position 128 and after. The standard symbols for the library also must exist for the UI. Standard English characters are always in the font set. The extension of the font file is *.SYM 

Check the _FONTS_  folder and you will find the font builder FONTEDIT.EXE. With the editor you can design the fonts for the desired language.  Just replace the Greek characters with your characters.

![FontEdit](https://github.com/user-attachments/assets/c3dea570-af49-4926-b602-8ffd8468470a)

Open a DOSBox terminal and write `loadfont macedon.syb` to load a new font set

![Loadfont](https://github.com/user-attachments/assets/7091fa38-8619-494b-bd4b-55b8838a11bb)

or write `fontedit.exe` to load the editor and press F5 to load an existing font set from the file (just type the name i.e macedon)

![image](https://github.com/user-attachments/assets/a1cdfff8-21c4-4088-a516-75245282f52c)

The standard symbols used internally from the library are shown in the NORTON.SYB file.

![image](https://github.com/user-attachments/assets/13373891-6406-496a-b22c-0fc4751e4512)

**Comment by cocoabox** [comment]
I don't think the problem is the font editor.
I have tried to build/compile your code (with minor additions)

https://github.com/cocoabox/DOS-GUI-Norton-Style/tree/master

The build script is in [build.bat](https://github.com/cocoabox/DOS-GUI-Norton-Style/blob/master/build.bat) but 
- some files failed to compile (syntax error)
- testobj.pas (looks like a test application) failed to compile with an out-of-memory error - I think it's an issue with the code base being too large, not a problem with my virtual environment 
- the INC file generated by your conversion utility doesn't include the variable declaration ; it just emits "$hex,$hex,$hex..." literally; 
- some of your code has {$INCLUDE C:/bp7/obj/XXXXX.obj} hardcoded references

Do you still remember this code? (It looks like you did this when you were 19 years old... and you look way older in your profile pic now). Or do you think you can make it compile? 

I understand it's been quite a while, and if you'd like to not spend time on this, it's absolutely fine. But please add a note mentioning this code doesn't compile, that'd save people lots of time.

Many thanks

**Comment by sdancer75** [comment]
Apologies for the delayed response. I just reviewed your answer. Please give me some time to compile the code, and I will let you know.

**Comment by sdancer75** [comment]
Hello again! I successfully compiled the **TestObj.pas** file, as shown in the video.

https://youtu.be/JEPF6Yn4zrk


Remember to replace the hardcoded references with your own file paths. I created a new folder named **run_oop** and extracted all the *.PAS, *.ASM, and *.Obj files there.

Open BP7 and edit your file directories under the option menu. 

![image](https://github.com/user-attachments/assets/c89d4199-13a3-4ca4-9f2a-12c539b80b04)

If the BP7 compiler reports a "file not found" error, locate the missing file in your file system and update the path accordingly. For example, please check the file named "general.pas."

![image](https://github.com/user-attachments/assets/691319d3-7bee-4bad-8cad-9b97e64db014)

**Comment by sdancer75** [comment]
I created a folder named "includes" to store the font used in my apps. The complete font set I use is the **elingr.inc**, that can also be found in the fonts folder.


![image](https://github.com/user-attachments/assets/f209b2be-963b-4721-aed2-b98ebca5330d)

**Comment by sdancer75** [comment]
Good news: I found the original QSORT.PAS source code. I added this to the QSORT folder, but I also included the English-translated file QSORT_EN.PAS.

The original help source file has also been added, but it needs to be compiled.
